name: Run Robot Framework Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Chromium & ChromeDriver
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser chromium-chromedriver
          # Buat symlink jika perlu
          if [ ! -e /usr/bin/google-chrome ]; then
            sudo ln -s /snap/bin/chromium /usr/bin/google-chrome
          fi

      - name: Run Robot Framework Tests
        run: |
          robot -d results tests/

      - name: Upload Robot Framework Report
        uses: actions/upload-artifact@v4
        with:
          name: robot-report
          path: results/
